/** Standard definitions for financial and impact KPIs.
 *  Used by MetricTooltip across all dashboard pages. */
export const KPI_DEFINITIONS: Record<string, string> = {
  // Financial
  "Capital Deployed": "Total committed capital across all fund investments.",
  "Capital Called": "Total capital drawn down from LPs for this investment.",
  "Total Value": "Current fair market valuation plus cumulative distributions returned to LPs.",
  "Portfolio IRR": "Weighted annualized internal rate of return across all fund cash flows.",
  IRR: "Annualized internal rate of return based on cash flow timing — accounts for when capital was deployed, not just total return.",
  MOIC: "Multiple on Invested Capital — total value (valuation + distributions) divided by capital called. A 1.5x MOIC means $1.50 returned per $1 invested.",
  DPI: "Distributions to Paid-In — cash actually returned to LPs divided by capital called. Measures realized (cash-in-hand) returns.",
  RVPI: "Residual Value to Paid-In — current unrealized valuation divided by capital called. Measures paper gains not yet distributed.",
  "Revenue Growth": "Trailing twelve-month year-over-year revenue growth rate.",
  "Unrealized Gain": "Current valuation minus capital called — the paper profit not yet converted to cash.",
  Distributions: "Cumulative cash returned to LPs from this investment (dividends, exits, etc.).",
  "Holding Period": "Time since initial capital deployment.",
  Invested: "Total capital deployed into this investment.",
  Valuation: "Current fair market value based on latest valuation methodology.",
  "Avg MOIC": "Capital-weighted average MOIC across all portfolio investments.",
  "People Reached": "Total direct and indirect beneficiaries of the investment.",
  "Households Reached": "Unique households benefiting from the investment, de-duplicated from individual beneficiary counts using household-level identifiers.",
  "Jobs Created": "Total direct employment generated by the investment, including full-time equivalents across all operating geographies.",
  "CO\u2082 Avoided": "Metric tonnes of CO\u2082 equivalent emissions avoided or reduced, calculated against a baseline scenario using accepted methodologies.",
  "Women Beneficiaries": "Percentage of total direct beneficiaries who are women or girls, based on sex-disaggregated program data.",
  "At Risk": "Number of investments flagged as needing attention based on financial and impact performance.",
};
